### ISSUE TITLE
Issues with installing the latest version

### ISSUE THREAD

**Issue by cwaq820** [RasmussenLab/vamb#119]
thank you for your help.
I wonder what's wrong with my input.
my problem is as follows,
vamb --outdir sout --fasta /home/va/Downloads/out/final.contigs.fa --jgi /home/va/Downloads/at.tsv -o C
WARNING: Running Vamb on fewer than 50,000 sequences might cause overfitting of the VAE and poor results. Ideally, use 100k-5m sequences.
Traceback (most recent call last):
  File "/home/va/Downloads/enter/envs/binning/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/home/va/Downloads/enter/envs/binning/lib/python3.7/site-packages/vamb/__main__.py", line 476, in main
    logfile=logfile)
  File "/home/va/Downloads/enter/envs/binning/lib/python3.7/site-packages/vamb/__main__.py", line 219, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/home/va/Downloads/enter/envs/binning/lib/python3.7/site-packages/vamb/__main__.py", line 103, in calc_rpkm
    rpkms = vamb.vambtools.load_jgi(file)
  File "/home/va/Downloads/enter/envs/binning/lib/python3.7/site-packages/vamb/vambtools.py", line 407, in load_jgi
    raise ValueError('Input file format error: 5th column should contain variances.')
ValueError: Input file format error: 5th column should contain variances.

But my input file did have var like this,
contigName	contigLen	totalAvgDepth	final.sorted.bam	final.sorted.bam-var
k141_0	333	0.961749	0.961749	0.0369901
so why I got this error?

**Comment by jakobnissen** [comment]
This bug was fixed in c38ef15 - nearly two years ago.
The problem arose because I forgot to take into account that the 5th field of the header ends with a newline.
To solve it, upgrade to a newer version of Vamb.

**Comment by cwaq820** [comment]
thanks for your answer!
I used conda install vamb and update it but it still have the same problem. so I choose the order
 git clone https://github.com/RasmussenLab/vamb -b master
to install the latest version. Though I install vamb successfully, I still can't use it like this, 
Traceback (most recent call last):
  File "/home/cc/.local/bin/vamb", line 11, in <module>
    load_entry_point('vamb', 'console_scripts', 'vamb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/cc/Desktop/vamb/vamb/__init__.py", line 33, in <module>
    from . import cluster
  File "/home/cc/Desktop/vamb/vamb/cluster.py", line 27, in <module>
    _NORMALPDF = _DELTA_X * _torch.Tensor(
AttributeError: module 'torch' has no attribute 'Tensor',
what's wrong with me this time?

**Comment by jakobnissen** [comment]
It seems like something went wrong when you installed. Let's go through this.
First, when you installed using Conda, do you know which version you installed? You can check it in the Vamb log file `log.txt`, or in `vamb/__init__.py`, or perhaps using Conda itself.

Second - when you installed using `git clone` - did you also use `pip` to install the required dependencies as written in the README? Otherwise it could be an issue with having an old version of PyTorch. Which version of PyTorch do you have?

**Comment by cwaq820** [comment]
well, I check the version I installed with conda and the answer is (2,1,0). my order is conda install -c bioconda vamb, I also try to use conda to update it but it seems that nothing was changed.

**Comment by cwaq820** [comment]
and my PyTorch did have some problems so I‘m downloading the latest version.
thanks for your help again!

**Comment by cwaq820** [comment]
and my PyTorch did have some problems so I‘m downloading the latest version.
thanks for your help again!

**Comment by cwaq820** [comment]
dear author, I successfully installed the latest version.  Perherps my options can provide some help for you.
I install the pytorch in conda as READMD suggested. but the order conda install -c bioconda vamb will install vamb which version is (2,1,0),so I use pip to install the latest version and I receive the ideal result. I think perhaps there are someting wrong with the vamb in bioconda.
thank you so much!
